# In this notebook we are going to cover some fundamental concepts of tensor using tensor flow

More specifically we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensor and Numpy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPU and Tensor flow (or TPU)
* Excersise to try for yourself!

# Introduction to Tensor

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimmension of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Create a matrix
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another metrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) # Specifying the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# What is the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                    [10,11,12]],
                    [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we have created so far

* A scalar is a single number
* Vector is a number with direction (e.g wind speed and direction)
* Matrix a 2-dimensional array of number
* Tensor an n-dimensional array of numbers (when n can be any number, a 0-dimenssional tensor is a scalar, a 1-dimensional tensor is a vector)

Practicing to write some clean funtions

In [13]:
a=[k*k for k in range(10) if k%2==0]

In [14]:
print(a)

[0, 4, 16, 36, 64]


In [15]:
def su1(l):
  for i in range(l):
    if i%2 ==0:
      yield(i*i)

In [16]:
a=su1(10)

In [17]:
for i in a:
  print(i)

0
4
16
36
64


In [18]:
dir()

['In',
 'Out',
 '_',
 '_10',
 '_11',
 '_12',
 '_3',
 '_4',
 '_5',
 '_6',
 '_7',
 '_8',
 '_9',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a',
 'another_matrix',
 'exit',
 'get_ipython',
 'i',
 'matrix',
 'quit',
 'scalar',
 'su1',
 'tensor',
 'tf',
 'vector']

### Creating Tensors with tf variable

In [19]:
# Create the same tensor with tf.variable

Changeable_tensor = tf.Variable([10,7])
Unchangeable_tensor = tf.constant([10,7])

In [20]:
Changeable_tensor,Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# Lets change one element in changeable tensor
Changeable_tensor[0].assign(7)
Changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# Lets try to make changes in unchangeable tensor
#Unchangeable_tensor[0].assign(7)
#Unchangeable_tensor

### Creating Random Tensors

Random tensor are tensor of arbitrary size containing random numbers

In [23]:
# Create two random but the same tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are the equal
random_1,random_2,random_1==random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shufle the order of elements in a tensor

In [24]:
# Shuffle a tensor (valuable for when you want to shuffle your data so inhetrent order doent has any effect on the model)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
# Shuffle Tensor
tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [25]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

Learn more about random seed generation 
global seeds
operation seeds

The random seed is made with conjunction of global and random level seeds

If we want reproduce able random tensor we need to set both the seeds

### Other ways to make tensors

In [26]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors
The main difference in numpy arrays and tensors is that they can work on GPUS really well

In [28]:
# You can also turn Numpy arrays into Tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
When dealing with tensor you probably want to be aware of the following
* Shape
* Rank
* Axis or dimension
* Size


In [30]:
# Crate a rank 4 tensors (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape , rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of Dimensions: ", rank_4_tensor.ndim)
print("Element along 0 axis: " ,rank_4_tensor.shape[0])
print("Element along last axis: ", rank_4_tensor.shape[-1])
print("Total number elements in the tensors ", tf.size(rank_4_tensor))
print("Total number elements in the tensors ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of Dimensions:  4
Element along 0 axis:  2
Element along last axis:  5
Total number elements in the tensors  tf.Tensor(120, shape=(), dtype=int32)
Total number elements in the tensors  120


### Indexing tensors

Tensor can be indexed just like Python lists

In [34]:
# Get the first two elements of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[:2,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [36]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [38]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                            [3,4]]) 
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
# Get the last element of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
# Add in extra dimenssion to our rank 2 tensor
rank_3_tensor =rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
rank_3_tensor[:1,:,:]

<tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]]], dtype=int32)>

In [42]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors

#### Basic operations
 +, -, *, /

In [44]:
# You can add values to a tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
# Orignal tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [46]:
# Multiplication also wprks
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [47]:
# Subtraction if you want
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [48]:
# We can us the tensorflow builtin function

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [49]:
# These function are faster in case of huge tensors
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix Multiplication

In [50]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
# Matrix multiplication with python operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
tensor.shape

TensorShape([2, 2])

In [53]:
# Create a tensor (3,2)
x =tf.constant([[1,2],[3,4],[5,6]])
y= tf.constant([[7,8],[9,10],[11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [54]:
# Try to matrix multiply tensor of the same shape
#tf.matmul(x,y) # rows of first donont match with cols of other
a=tf.transpose(x)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [55]:
tf.matmul(a,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** The Dot Product **

Matrix multiplication is also called dot product.
you can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()

In [56]:
# Perform the dot product on x and y (requires  x or y to be transposed)
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [57]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
# Check the value of y, reshape y and transposed y
print("Normal y:")
print(y,"\n")
print("y reshaped:")
print(tf.reshape(y,shape=(2,3)),"\n")
print("transposed y:")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

transposed y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [59]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

### Changing the data type of a tensor

In [60]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [61]:
c = tf.constant([7,10])
c.dtype

tf.int32

In [62]:
# Change from float32 to float16
D =tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [63]:
# Change int32 to float32
E=tf.cast(c,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [64]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregate Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [65]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [66]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

lets go through the following form of aggregation
* Get minimum
* Get maximum
*Get mean of tensor
* Get sum of a tensor

In [67]:
# Create a random tensor with values from 0 to 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([36, 14, 27, 55, 75, 21, 46, 95,  5, 91, 97, 20, 39, 81, 99, 78, 43,
       37, 32,  1, 40, 86, 95,  5, 40, 18, 47, 80, 89, 43, 86, 41, 39, 51,
       81, 33, 50,  8, 21, 84, 90, 41, 68, 90, 20, 88,  7, 71, 65,  9])>

In [68]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [69]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [70]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [71]:
# Find the Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2578>

In [72]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([36, 14, 27, 55, 75, 21, 46, 95,  5, 91, 97, 20, 39, 81, 99, 78, 43,
       37, 32,  1, 40, 86, 95,  5, 40, 18, 47, 80, 89, 43, 86, 41, 39, 51,
       81, 33, 50,  8, 21, 84, 90, 41, 68, 90, 20, 88,  7, 71, 65,  9])>

In [73]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=903>

In [74]:
tf.math.reduce_std(tf.cast(E,dtype=np.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.053392>

Check the error type and go to the doccumentation and check the input they are giving


### Find the positional maximum and minimum



In [75]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [76]:
# Find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [77]:
# Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [78]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [79]:
# Check for equality
f[tf.argmax(f)]==tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [80]:
# Find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [81]:
# Find the minimum using the postional minimum index
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [82]:
tf.random.set_seed(42)
G =tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [83]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [84]:
G_squeezed = tf.squeeze(G)

In [85]:
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encode tensors

In [86]:
# Create a list of indices
some_list = [0,1,2,3] # Could be red green blue purple
tf.one_hot(some_list , depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [87]:
# Specify custom value for one hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning" , off_value="b I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'b I also like to dance',
        b'b I also like to dance', b'b I also like to dance'],
       [b'b I also like to dance', b'yo I love deep learning',
        b'b I also like to dance', b'b I also like to dance'],
       [b'b I also like to dance', b'b I also like to dance',
        b'yo I love deep learning', b'b I also like to dance'],
       [b'b I also like to dance', b'b I also like to dance',
        b'b I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Squaring, Log , square root

In [88]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [89]:
# Square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [90]:
# Method requires non int type
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [91]:
# Find the log 
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensor flow interacts beautifuly with numpy arrays

In [92]:
# Create a tensor directly from Numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [93]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [94]:
# Convert tensor J to a Numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [95]:
# The default types of each are slightly different 
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# Check the datatypeof each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUS

In [97]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [98]:
!nvidia-smi

Wed Oct 26 03:46:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    26W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

** NOTE ** If you have access to a cuda enabled GPU Tensor flow will automatically use it

In [108]:
# Finding grocery bill using tensors
items_monthly = tf.random.uniform(maxval=10,shape=(3,30),dtype=tf.int32)
items_Monthly = tf.transpose(items_monthly)
items_Monthly

<tf.Tensor: shape=(30, 3), dtype=int32, numpy=
array([[9, 0, 0],
       [5, 7, 6],
       [8, 5, 0],
       [8, 7, 6],
       [3, 7, 7],
       [8, 6, 0],
       [1, 6, 5],
       [0, 6, 0],
       [2, 1, 4],
       [6, 3, 6],
       [5, 4, 3],
       [7, 2, 2],
       [3, 5, 4],
       [0, 3, 5],
       [8, 5, 8],
       [3, 6, 8],
       [9, 2, 5],
       [7, 2, 6],
       [7, 1, 6],
       [2, 4, 7],
       [1, 8, 2],
       [3, 2, 5],
       [0, 3, 4],
       [2, 7, 5],
       [5, 6, 9],
       [4, 1, 1],
       [1, 8, 9],
       [3, 8, 2],
       [9, 9, 8],
       [7, 2, 6]], dtype=int32)>

In [109]:
items_price = tf.constant([[10],[20],[30]])
items_price.shape

TensorShape([3, 1])

In [111]:
per_day_bill = items_Monthly @ items_price

In [115]:
monthly_expence = sum(per_day_bill)
monthly_expence

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8250], dtype=int32)>

In [118]:
yearly_expence = 12*monthly_expence
yearly_expence

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([99000], dtype=int32)>